src/Entity/Track.php
<?php

namespace App\Entity;

use App\Repository\TrackRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrackRepository::class)]
class Track
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'tracks')]
    private ?Album $album = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column(length: 255, nullable: false, options: ["default" => ""])]
    private ?string $spotifyUri = null;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->album->getImage();
    }

    public function getSpotifyUri(): ?string
    {
        return $this->spotifyUri;
    }

    public function setSpotifyUri(?string $spotifyUri): self
    {
        $this->spotifyUri = $spotifyUri;

        return $this;
    }


    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    public function setAlbum(?Album $album): self
    {
        $this->album = $album;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDurationMinuteString(): ?String
    {
        $totalSeconds = $this->duration / 1000;
        $minutes = floor($totalSeconds / 60);
        $seconds = $totalSeconds % 60;
    
        return $minutes . "min" . $seconds . "s";
    }
}

src/Form/TrackType.php
<?php

namespace App\Form;

use App\Entity\Track;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrackType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('duration')
            ->add('album')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Track::class,
        ]);
    }
}

src/Controller/TrackController.php
<?php

namespace App\Controller;

use App\Entity\Track;

use App\Entity\Album;
use App\Controller\AlbumController;

use App\Form\TrackType;
use App\Repository\TrackRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/track')]
class TrackController extends AbstractController
{
    #[Route('/{albumid}', name: 'app_track_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager, $albumid): Response
    {
        $albumid = intval($albumid);
        $albums = $entityManager
            ->getRepository(Album::class)
            ->findAll();
        $album = $entityManager->getRepository(Album::class)->find($albumid);

        $tracks = $album->getTracks();
        return $this->render('track/index.html.twig', [
            'tracks' => $tracks,
            'album' => $album,
            'albums' => $albums
        ]);
    }

    #[Route('/new/{albumid}', name: 'app_track_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TrackRepository $trackRepository, Album $albumid): Response
    {
        
        $track = new Track();
        if(is_null($track->getAlbum())){
            $track->setAlbum($albumid);
        }
        $form = $this->createForm(TrackType::class, $track);
        $form->handleRequest($request);

        
        if ($form->isSubmitted() && $form->isValid()) {
            $trackRepository->save($track, true);

            return $this->redirectToRoute('app_track_index', array('albumid'=> $track->getAlbum()->getId()), Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('track/new.html.twig', [
            'track' => $track,
            'form' => $form,
            'album' => $albumid,
        ]);
    }

    #[Route('/{id}', name: 'app_track_show', methods: ['GET'])]
    public function show(Track $track): Response
    {
        return $this->render('track/show.html.twig', [
            'track' => $track,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_track_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Track $track, TrackRepository $trackRepository): Response
    {
        $form = $this->createForm(TrackType::class, $track);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trackRepository->save($track, true);

            return $this->redirectToRoute('app_track_index', array('albumid'=> $track->getAlbum()->getId()), Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('track/edit.html.twig', [
            'track' => $track,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_track_delete', methods: ['POST'])]
    public function delete(Request $request, Track $track, TrackRepository $trackRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$track->getId(), $request->request->get('_token'))) {
            $trackRepository->remove($track, true);
        }

        return $this->redirectToRoute('app_track_index',  array('albumid'=> $track->getAlbum()->getId()), Response::HTTP_SEE_OTHER);
    }
}

templates/track/_delete_form.html.twig
<form method="post" action="{{ path('app_track_delete', {'id': track.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ track.id) }}">
    <button id="button-delete" ><img src="{{ asset('img/delete.png') }}" id="img-edit" style="max-width: 80%; height: 2rem;"></button>
</form>


                                    

templates/track/edit.html.twig
{% extends 'base.html.twig' %}


{% block title %}Modifier la musique{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/style.css') }}">
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center mt-4">Modifier la musique</h1>
    <div class="row mt-5 justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card artist-card">
                <div class="card-body">
                    <div class="form-group">
                        {{ form_start(form) }}
                            {{ form_row(form.name, {
                                label: 'Titre de la musique',
                                'attr': {
                                    'class': 'form-control mb-3',
                                    'placeholder': 'Entrez le titre de la musique'
                                }
                            }) }}
                            {{ form_row(form.duration, {
                                label: 'Durée',
                                'attr': {
                                    'class': 'form-control mb-3',
                                    'placeholder': 'Entrez la durée de la musique en milliseconde'
                                }
                            }) }}
                            {{ form_row(form.album, {
                                label: 'Album',
                                'attr': {
                                    'class': 'form-control mb-3',
                                },
                                'choice_attr': {
                                    'selected': 'selected',
                                },
                            }) }}
                            <button type="submit" class="btn btn-outline-light btn-rounded">Mettre à jour la musique</button>
                        {{ form_end(form) }}
                    </div>
                </div>

        <div class="col text-center mb-4">
            {{ include('track/_delete_form.html.twig') }}
    </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col text-center">
            <a href="{{ path('app_track_index', {'albumid': track.album.id}) }}" class="btn btn-secondary">Retour à la liste des musiques</a>
        </div>
    </div>
    
</div>
{% endblock %}

templates/track/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Track index{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block sidebar">
            <div class="sidebar-sticky pt-3 navigation-album" >
                <div class="logo_flopify">
                    <img src="{{ asset('img/logo_flopify.png') }}" style="max-width: 80%; height: 5rem;">
                    <h4 class="text-white" style="margin-top: auto; margin-bottom: auto;">Flopify</h4>
                </div>
                            <ul class="nav flex-column overflow-auto flex-nowrap">

                <li class="nav-item">
                    <button class="create-album-button">
                    <div class="svg-background">
                        <svg role="img" height="12" width="12" aria-hidden="true" viewBox="0 0 16 16" data-encore-id="icon" class="btn-add-svg" fill="none">
                            <path d="M13.5 1.515a3 3 0 0 0-3 0L3 5.845a2 2 0 0 0-1 1.732V21a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-6h4v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V7.577a2 2 0 0 0-1-1.732l-7.5-4.33z" fill="#000"></path>
                        </svg>
                    </div>
                    <a href="{{ path('app_album_index') }}" class="nav-link">Accueil</a>
                </button>
                </li>
                <li class="nav-item">
                        <button class="create-album-button">
                            <div class="svg-background">
                                <svg role="img" height="12" width="12" aria-hidden="true" viewBox="0 0 16 16" data-encore-id="icon" class="btn-add-svg" fill="none">
                                    <path d="M8 0C3.58 0 0 3.58 0 8s3.58 8 8 8 8-3.58 8-8-3.58-8-8-8zm0 14.5c-1.33 0-2.42-.26-3.25-.67C6.28 12.62 8 10.67 8 10.67s1.72 1.95 3.25 3.16c-.83.41-1.92.67-3.25.67zm0-11c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3zm0 1.5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5-1.5-.67-1.5-1.5.67-1.5 1.5-1.5z" fill="#000"></path>
                                </svg>
                            </div>
                            <a href="{{ path('app_artist_index') }}" class="nav-link">Voir les artistes</a>
                        </button>
                    </li>
                <li class="nav-item">
                <button class="create-album-button">
                    <div class="svg-background">
                        <svg role="img" height="12" width="12" aria-hidden="true" viewBox="0 0 16 16" data-encore-id="icon" class="btn-add-svg" fill="none">
                            <path d="M15.25 8a.75.75 0 0 1-.75.75H8.75v5.75a.75.75 0 0 1-1.5 0V8.75H1.5a.75.75 0 0 1 0-1.5h5.75V1.5a.75.75 0 0 1 1.5 0v5.75h5.75a.75.75 0 0 1 .75.75z" fill="#000"></path>
                        </svg>
                    </div>
                    <a href="{{ path('app_track_new', {'albumid': album.id}) }}" class="nav-link">Créer une musique</a>
                </button>
                </li>
            
                {# Add more navigation links here #}
            </ul>
            <h4 class="text-white mt-4 mb-4">Album</h4>
            <ul class="nav liste-album" >
                {% for album in albums %}
                    <li                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ path('app_track_index', {'albumid': album.id}) }}">{{ album.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </nav>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    {{ include('nav_bar_haut.html.twig') }}

        <div class="album-info">
            <div class="album-info-gauche"> 
                <img src="{{ album.image }}" alt="{{ album.name }}" class="album-cover">
                <h2 class="album-title">{{ album.name }}</h2>
            </div>
            <div class="album-info-droite"> 
                <a class="btn" id="btn-edit-album" href="{{ path('app_album_edit', {'id' :album.id}) }}">Modifier l'album</a>
                {{ include('album/_delete_form.html.twig') }}
            </div>
        </div>
        <div class="track-list">
            <ul class="list-track-item">
                {% for track in tracks %}
                    <li>
                        <div class="track-item">
                            <div class="track-detail">
                                <span >{{ track.name }}</span>
                                <span >{{ track.album.artist }}</span>
                            </div>
                            <div class="track-droite">
                                <span class="track-duration">{{ track.getDurationMinuteString() }}</span>
                                <a href="{{ path('app_track_edit', {'id' :track.id}) }}">
                                    <img src="{{ asset('img/edit.png') }}" id="img-edit" style="max-width: 80%; height: 2rem;">
                                </a>
                                {{ include('track/_delete_form.html.twig') }}
                                
                            </div>
                        </div>
                    </li>
                {% else %}
                    <p class="text-center text-white">Aucun enregistrement trouvé</p>
                {% endfor %}
            <ul>
        </div>

    
        
    </main>
</div>
</div>

{% endblock %}

{% block stylesheets %}
{{ parent() }}
<style>
    main {
    background: linear-gradient(180deg, #84796d, #121212 30%, #121212);
    padding-top: 60px;
    min-height: 100vh; /* Ajouté pour étendre la hauteur minimale à 100% de la fenêtre du navigateur */
    }


    .navigation-album{
        background-color: #000000;
    }

    .sidebar {
        height: 100vh;
        padding-right: 0;
        padding-left: 0;
        position: fixed;
    }


    body, button, input, select, textarea {
        font-family: CircularSp, CircularSp-Arab, CircularSp-Hebr, CircularSp-Cyrl, CircularSp-Grek, CircularSp-Deva, var(--fallback-fonts,), sans-serif;
    }

    .create-album-button {
        display:    flex;
        align-items: center;
        background-color: transparent;
        border: none;
        cursor: pointer;
        padding: 8px;
    }

    .create-album-button:hover .svg-background {
        background-color: #fff;
    }

    .nav-link{
        color: #b3b3b3;
    }

    .create-album-button:hover {
        color: #fff;
    }

    .svg-background {
        background-color: #b3b3b3;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 20px;
        height: 20px;
        margin-right: 5px;
    }

    .btn-add-svg {
        margin: 0;
        fill: #b3b3b3;
    }

    .create-album-button:hover .btn-add-svg {
        fill: #fff;
    }

    .logo_flopify{
        display:flex;
    }



.main-navbar {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 1020;
    width: 100%;
    background-color: inherit;
}

@media (min-width: 768px) {
    .main-navbar {
        left: 300px;
        width: calc(100% - 300px);
    }
}



.liste-album {
  display: flex;
  flex-wrap: wrap;
  overflow-y: auto;
  max-height: 80vh; /* limit the height to avoid overflow */
}


.album-cover {
    width: 150px;
    height: 150px;
    margin-right: 20px;
}

.album-title {
    color: #ffffff;
    font-size: 24px;
    font-weight: bold;
}

.track-list {
    width: 100%;
}

.track-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px;
    transition: background-color 0.3s;
}

.track-item:hover {
    background-color: #383838;
}

.track-item:hover #img-edit{
    background-color: white;
    border-radius: 50%;
    padding: 1px;
}

.album-info {
    display: flex;
    align-items: center;
    margin-bottom: 20px;
    padding: 20px;
    border-radius: 10px;
}

.album-info-droite {
    display: flex;
}

.list-track-item{
    list-style-type: none;
}
.track-detail{
   color: #ffffff;
   font-size: 14px; 
}

.track-detail span{
    display: block;}
/* Style the duration */

.track-duration {
    color: #ffffff;
    font-size: 14px;
}

.track-droite{
    display:flex;
    flex-wrap: nowrap;
}

#button-delete{
    border: none;
    background-color: transparent;
    padding: 0;
    cursor: pointer;
    outline: none;
}

#button-delete img {
    max-width: 80%;
    height: 2rem;
    vertical-align: middle;
}

#btn-edit-album {
 display: inline-block;
 padding: 0.9rem 1.8rem;
 font-size: 16px;
 font-weight: 700;
 color: white;
 border: 3px solid rgb(176, 242, 182);
 cursor: pointer;
 position: relative;
 background-color: transparent;
 text-decoration: none;
 overflow: hidden;
 z-index: 1;
 font-family: inherit;
}

#btn-edit-album::before {

 content: "";
 position: absolute;
 left: 0;
 top: 0;
 width: 100%;
 height: 100%;
 background-color: rgb(176, 242, 182);
 transform: translateX(-100%);
 transition: all .3s;
 z-index: -1;
}

#btn-edit-album:hover::before {
 transform: translateX(0);
}

#btn-edit-album:hover{
color:black;
}

</style>

{% endblock %}

{% block javascripts %}
<script>
    {{ parent() }}

    $(document).ready(function() {
    console.log("test");
    const ul = document.querySelector('.liste-album');

    ul.addEventListener('wheel', (evt) => {
        evt.preventDefault();
        ul.scrollBy({
            top: evt.deltaY * 0.5,
            behavior: 'smooth'
        });
    });
});
    
</script>
{% endblock %}

templates/track/new.html.twig
{% extends 'base.html.twig' %}


{% block title %}Ajouter une musique{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/style.css') }}">
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center mt-4">Ajouter une musique</h1>
    <div class="row mt-5 justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
            <div class="card artist-card">
                <div class="card-body">
                    <div class="form-group">
                        {{ form_start(form) }}
                            {{ form_row(form.name, {
                                label: 'Titre de la musique',
                                'attr': {
                                    'class': 'form-control mb-3',
                                    'placeholder': 'Entrez le titre de la musique'
                                }
                            }) }}
                            {{ form_row(form.duration, {
                                label: 'Durée',
                                'attr': {
                                    'class': 'form-control mb-3',
                                    'placeholder': 'Entrez la durée de la musique en milliseconde'
                                }
                            }) }}
                            {{ form_row(form.album, {
                                label: 'Album',
                                'attr': {
                                    'class': 'form-control mb-3',
                                },
                                'choice_attr': {
                                    'selected': 'selected',
                                },
                            }) }}
                            <button type="submit" class="btn btn-outline-light btn-rounded">Ajouter la musique</button>
                        {{ form_end(form) }}
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col text-center">
            <a href="{{ path('app_track_index', {'albumid': album.id}) }}" class="btn btn-secondary">Retour à la liste des musiques</a>
        </div>
    </div>
    
</div>
{% endblock %}

templates/track/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Track{% endblock %}

{% block body %}
    <h1>Track</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ track.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ track.name }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ track.image }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_track_index') }}">back to list</a>

    <a href="{{ path('app_track_edit', {'id': track.id}) }}">edit</a>

    {{ include('track/_delete_form.html.twig') }}
{% endblock %}